config/routes.rb
<<<<<<< HEAD
RedmineApp::Application.routes.draw do
  get "/projects/:id/dmsf", :controller => 'dmsf', :action => 'index'
  get "/projects/:id/dmsf/*dmsf_path", :controller => 'dmsf', :action => 'index', :as => 'dmsf_index', :format => false
  
  # Approval workflow    
  resources :dmsf_workflows do
    member do
      get 'autocomplete_for_user'
      get 'action'
      post 'new_action'
    end
  end
  
  match 'dmsf_workflows/:id/edit', :controller => 'dmsf_workflows', :action => 'add_step', :id => /\d+/, :via => :post
  match 'dmsf_workflows/:id/edit', :controller => 'dmsf_workflows', :action => 'remove_step', :id => /\d+/, :via => :delete
  match 'dmsf_workflows/:id/edit', :controller => 'dmsf_workflows', :action => 'reorder_steps', :id => /\d+/, :via => :put  
end
=======
# Redmine plugin for Document Management System "Features"
#
# Copyright (C) 2011   Vít Jonáš <vit.jonas@gmail.com>
# Copyright © 2012 Daniel Munn <dan.munn@munnster.co.uk>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

RedmineApp::Application.routes.draw do

  #
  # dmsf controller
  #   /projects/<project>/dmsf
  #   [As this controller also processes 'folders' it maybe better to branch into a folder route rather than leaving it as is]
  ##
  post '/projects/:id/dmsf/create', :controller => 'dmsf', :action => 'create'
  post '/projects/:id/dmsf/notify/activate', :controller => 'dmsf', :action => 'notify_activate'
  post '/projects/:id/dmsf/notify/deactivate', :controller => 'dmsf', :action => 'notify_deactivate'
  post '/projects/:id/dmsf/delete', :controller => 'dmsf', :action => 'delete'
  post '/projects/:id/dmsf/save', :controller => 'dmsf', :action => 'save'
  post '/projects/:id/dmsf/save/root', :controller => 'dmsf', :action => 'save_root'
  post '/projects/:id/dmsf/entries', :controller => 'dmsf', :action => 'entries_operation'
  post '/projects/:id/dmsf/entries/delete', :controller => 'dmsf', :action => 'delete_entries'
  post '/projects/:id/dmsf/entries/email', :controller => 'dmsf', :action => 'entries_email'
  post '/projects/:id/dmsf/lock', :controller => 'dmsf', :action => 'lock'
  post '/projects/:id/dmsf/unlock', :controller => 'dmsf', :action => 'unlock'
  get '/projects/:id/dmsf/', :controller => 'dmsf', :action => 'show'
  get '/projects/:id/dmsf/new', :controller => 'dmsf', :action => 'new'
  get '/projects/:id/dmsf/edit', :controller=> 'dmsf', :action => 'edit'
  get '/projects/:id/dmsf/edit/root', :controller=> 'dmsf', :action => 'edit_root'

  #
  # dmsf_state controller
  #   /projects/<project>/dmsf/state
  ##
  post '/projects/:id/dmsf/state', :controller => 'dmsf_state', :action => 'user_pref_save'


  #
  #  dmsf_upload controller
  #   /projects/<project>/dmsf/upload - dmsf_upload controller
  ##

  post '/projects/:id/dmsf/upload/files', :controller => 'dmsf_upload', :action => 'upload_files'
  post '/projects/:id/dmsf/upload/file', :controller => 'dmsf_upload', :action => 'upload_file'
  post '/projects/:id/dmsf/upload/commit', :controller => 'dmsf_upload', :action => 'commit_files'
  
  #
  # dmsf_files controller
  #   /dmsf/files/<file id>
  ##
  post '/dmsf/files/:id/notify/activate', :controller => 'dmsf_files', :action => 'notify_activate'
  post '/dmsf/files/:id/notify/deactivate', :controller => 'dmsf_files', :action => 'notify_deactivate'
  post '/dmsf/files/:id/lock', :controller => 'dmsf_files', :action => 'lock'
  post '/dmsf/files/:id/unlock', :controller => 'dmsf_files', :action => 'unlock'
  post '/dmsf/files/:id/delete', :controller => 'dmsf_files', :action => 'delete'
  post '/dmsf/files/:id/revision/create', :controller => 'dmsf_files', :action => 'create_revision'
  post '/dmsf/files/:id/revision/delete', :controller => 'dmsf_files', :action => 'delete_revision'
  get '/dmsf/files/:id/download', :controller => 'dmsf_files', :action => 'show', :download => '' #Otherwise will not route nil download param
  get '/dmsf/files/:id/download/:download', :controller => 'dmsf_files', :action => 'show'
  get '/dmsf/files/:id', :controller => 'dmsf_files', :action => 'show'
  # Just to keep backward compatibility of external url links
  get '/dmsf_files/:id', :controller => 'dmsf_files', :action => 'show'

  #
  # files_copy controller
  #   /dmsf/files/<file id>/copy
  ##
  post '/dmsf/files/:id/copy/create', :controller => 'dmsf_files_copy', :action => 'create'
  post '/dmsf/files/:id/copy/move', :controller => 'dmsf_files_copy', :action => 'move'
  get '/dmsf/files/:id/copy', :controller => 'dmsf_files_copy', :action => 'new'

  #
  # folders_copy controller
  #   /dmsf/folders/<folder id>/copy
  ##
  #verify :method => :post, :only => [:copy_to], :render => { :nothing => true, :status => :method_not_allowed }
  post '/dmsf/folders/:id/copy/to', :controller => 'dmsf_folders_copy', :action => 'copy_to'
  get '/dmsf/folders/:id/copy', :controller => 'dmsf_folders_copy', :action => 'new'

  #
  # DAV4Rack implementation of Webdav [note: if changing path you'll need to update lib/redmine_dmsf/webdav/no_parse.rb also]
  #   /dmsf/webdav
  mount DAV4Rack::Handler.new(
    :root_uri_path => "/dmsf/webdav",
    :resource_class => RedmineDmsf::Webdav::ResourceProxy,
    :controller_class => RedmineDmsf::Webdav::Controller
  ), :at => "/dmsf/webdav"
end
>>>>>>> master

app/controllers/dmsf_workflows_controller.rb
class DmsfWorkflowsController < ApplicationController
  unloadable  
  layout :workflows_layout
  
  before_filter :find_workflow, :except => [:create, :new, :index]  
  before_filter :find_project   
  before_filter :authorize_global, :except => [:action, :new_action]
  
  def index    
    if @project
      @workflow_pages, @workflows = paginate Dmsf::Workflow.where(:project_id => @project.id), :per_page => 25    
    else
      @workflow_pages, @workflows = paginate Dmsf::Workflow.where(:project_id => nil), :per_page => 25    
    end
  end
  
  def action
  end
  
  def new_action
    logger.info '>>>>>>>>>>>>>>>>>>>>>>> YES!'
  end

  def log
  end
  
  def new   
    @workflow = Dmsf::Workflow.new        
  end
  
  def create
    @workflow = Dmsf::Workflow.new(:name => params[:dmsf_workflow][:name], :project_id => params[:project_id])
    if request.post? && @workflow.save
      flash[:notice] = l(:notice_successful_create)
      if @project
        redirect_to settings_project_path(@project, :tab => 'dmsf')
      else
        redirect_to dmsf_workflows_path
      end
    else      
      render :action => 'new'
    end
  end
  
  def edit       
  end   
  
  def update    
    if request.put? && @workflow.update_attributes({:name => params[:dmsf_workflow][:name]})
      flash[:notice] = l(:notice_successful_update)
      if @project
        redirect_to settings_project_path(@project, :tab => 'dmsf')
      else
        redirect_to dmsf_workflows_path
      end    
    else      
      render :action => 'edit'
    end
  end
  
  def destroy    
    begin
      @workflow.destroy    
    rescue
      flash[:error] = l(:error_unable_delete_dmsf_workflow)
    end
    if @project
      redirect_to settings_project_path(@project, :tab => 'dmsf')
    else
      redirect_to dmsf_workflows_path
    end    
  end
  
  def autocomplete_for_user
    respond_to do |format|      
      format.js
    end        
  end
  
  def add_step     
    if request.post?      
      users = User.find_all_by_id(params[:user_ids])      
      if params[:step] == '0'
        if @workflow.steps.count > 0
          step = @workflow.steps.last + 1
        else
          step = 1
        end
      else
        step = params[:step].to_i
      end
      operator = 1 ? params[:commit] == l(:dmsf_and) : 0      
      users.each do |user|
        @workflow.workflow_steps << Dmsf::WorkflowStep.new(
          :workflow_id => @workflow.id, 
          :step => step, 
          :user_id => user.id, 
          :operator => operator)
      end   
      @workflow.save      
    end             
    respond_to do |format|
      format.html            
    end        
  end
  
  def remove_step        
    if request.delete?
      Dmsf::WorkflowStep.where(:workflow_id => @workflow.id, :step => params[:step]).each do |ws|
        @workflow.workflow_steps.delete(ws)
      end              
      @workflow.workflow_steps.each do |ws|
        n = ws.step.to_i
        if n > params[:step].to_i        
          ws.step = n - 1
          ws.save
        end
      end
    end        
    respond_to do |format|
      format.html      
    end
  end
  
  def reorder_steps    
    if request.put?
      @workflow.reorder_steps params[:step].to_i, params[:workflow_step][:move_to]      
    end        
    respond_to do |format|
      format.html      
    end
  end
  
  private    
  
  def find_workflow   
    @workflow = Dmsf::Workflow.find_by_id(params[:id])    
  end
    
  def find_project    
    if @workflow
      @project = @workflow.project
    elsif params[:project_id].present?
       @project = Project.find_by_id params[:project_id]
    end              
  end
  
  def workflows_layout
    find_workflow
    find_project
    @project ? 'base' : 'admin'
  end
end

app/views/dmsf_workflows/_action.html.erb
<h3 class="title"><%= l(:label_dmsf_workflow) %></h3>

<%= form_tag({:controller => 'dmsf_workflows',
              :action => 'new_action',
              :object_type => Dmsf::Workflow,
              :object_id => @workflow,
              :project_id => @project},
              :remote => true,
              :method => :post,
              :id => 'new-action-form') do %>
  <p><label><%= radio_button_tag 'action', 'approve', true %> <%= l(:label_dmsf_wokflow_action_approve) %></label><br/></p>
  
  <p>
    <label><%= radio_button_tag 'action', 'reject' %> <%= l(:label_dmsf_wokflow_action_reject) %></label><br/>
    <%= text_area_tag :note, '', :placeholder => l(:message_dmsf_wokflow_note), :size => '38x2' %>
  </p>

  <p>
    <label><%= radio_button_tag 'action', 'delegate' %> <%= l(:label_dmsf_wokflow_action_delegate) %></label><br/>
    <%= text_field_tag 'user_search', nil %>
  </p>
  
  <%= javascript_tag "observeSearchfield('user_search', 'users_for_delegate', '#{ escape_javascript autocomplete_for_user_dmsf_workflow_path(@workflow) }')" %>

  <div id="users_for_delegate">
    <%= principals_check_box_tags 'watcher[user_ids][]', @workflow.delegates %>
  </div>

  <p class="buttons">
    <%= submit_tag l(:button_add), :name => nil, :onclick => "hideModal(this);" %>
    <%= submit_tag l(:button_cancel), :name => nil, :onclick => "hideModal(this);", :type => 'button' %>
  </p>
<% end %>

app/views/dmsf_workflows/_steps.html.erb
<% if @workflow.project %>
  <h2><%= link_to l(:label_dmsf_workflow_plural), settings_project_path(@project, :tab => 'dmsf') %> &#187; <%=h @workflow %></h2>
<% else %>
  <h2><%= link_to l(:label_dmsf_workflow_plural), dmsf_workflows_path %> &#187; <%=h @workflow %></h2>
<% end %>

<%= labelled_form_for @workflow do |f| %>
  <%= error_messages_for 'workflow' %>
  <div class="box tabular">
    <p><%= f.text_field :name, :required => true %><%= submit_tag l(:button_save) %></p>
  </div>  
<% end %>    

<div class="tab-content" id="tab-content-members">
 
<div class="splitcontentleft">  
<% if @workflow.steps.any? %>
<table class="list steps">
  <thead><tr>
    <th><%= l(:label_dmsf_workflow_step) %></th>
    <th><%= l(:label_dmsf_workflow_approval_plural) %></th>
    <th><%=l(:button_sort)%></th>
    <th style="width:15%"></th>          
  </tr></thead>
  <tbody>  
  <% @workflow.steps.each do |step| %>    
    <tr id="step-<%= step %>" class="<%= cycle 'odd', 'even' %> step">            
      <td class="step"><%= step %></td>
      <td class="approval">
        <% @workflow.approvals(step).each_with_index do |approval, i| %>
          <% if i != 0 %>
            <b><%= approval.soperator %></b>&nbsp
          <% end %>
          <%= link_to_user approval.user %>
        <% end %>
      </td>  
      <td align="center" style="width:15%;">
        <%= reorder_links('workflow_step', {:action => 'edit', :id => @workflow, :step => step}, :put) %>
      </td>
      <td class="buttons">      
        <%= delete_link edit_dmsf_workflow_path(@workflow, :step => step) %>
      </td>  
    </tr>
  <% end; reset_cycle %>
  </tbody>
</table>
<% else %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% end %>
</div>

<div class="splitcontentright">
  <%= form_for(@workflow, :url => edit_dmsf_workflow_path(@workflow),
               :html => {:method => :post}) do |f| %>    
    <fieldset><legend><%=l(:label_user_new)%></legend>

    <p><%= label_tag 'user_search', l(:label_user_search) %><%= text_field_tag 'user_search', nil %></p>    
    <%= javascript_tag "observeSearchfield('user_search', null, '#{ escape_javascript autocomplete_for_user_dmsf_workflow_path(@workflow) }')" %>
    
    <div id="users">
      <%= render_principals_for_new_dmsf_workflow_users(@workflow) %>
    </div>

    <p>
      <%= l(:label_dmsf_workflow_step) %>
      <%= select_tag 'step',
              dmsf_workflow_steps_options_for_select(@workflow.steps),
              :id => 'selected_step', :style => "width:100px" %>              
    </p>
    <p><%= submit_tag l(:dmsf_and) %>&nbsp<%= submit_tag l(:dmsf_or) %></p>
    </fieldset>
  <% end %>
</div>

</div>

app/views/dmsf_workflows/action.js.erb
$('#ajax-modal').html('<%= escape_javascript(render :partial => 'action', :locals => {:workflow => @workflow}) %>');
showModal('ajax-modal', '400px');
$('#ajax-modal').addClass('new-action');

app/views/dmsf_workflows/reorder_steps.html.erb
<%= render 'steps' %>